### ISSUE TITLE
Missing API v2 Documentation

### ISSUE THREAD

**Issue by funkaoshi** [sdelements/slate#13]
We are missing API v2 docs for the following existing endpoints:

- [x] Phases /api/v2/phases
- [x] Task Statuses /api/v2/taskstatuses [Leta]
- [x] Report Settings /api/v2/report-settings
- [ ] Organizations /api/v2/organizations
- [x] Profiles /api/v2/profiles
- [x] Library /api/v2/library [Shawn, Emin]
- [x] Notes /api/v2/??? [Leta, Simon]
- [x] Tasks /api/v2/project/1/tasks [Ian, Jeff]

**Comment by funkaoshi** [comment]
Phases addressed in pull request #12.

**Comment by notsrg** [comment]
Library Standards and Weaknesses address in PR #14

**Comment by lmontopo** [comment]
I'm going to take Task Statuses!

**Comment by lmontopo** [comment]
Is profiles not already in the docs?  Maybe its incomplete?

**Comment by funkaoshi** [comment]
I might not have looked carefully.

**Comment by lmontopo** [comment]
The report settings docs are in WIP merge request.  Need a bit of feedback/help.

**Comment by lmontopo** [comment]
Just talked with Hanif, we need to talk with @funkaoshi and others to decide if we want to keep the report-settings documentation or not.

**Comment by funkaoshi** [comment]
I'm going to leave report-settings and organization off the books. I don't consider either 'public'.
